import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Quicklinks from "./components/Quicklinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FI Marketing Agency",
  description: "Generated by FI Marketing Agency",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        {children}
        <Quicklinks/>
        <Footer/>
        </body>
    </html>
  );
}
